/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgentRouteImport } from './routes/app/agent'
import { Route as AppCareerRouteImport } from './routes/app/career'
import { Route as AppDiagnosticRouteImport } from './routes/app/diagnostic'
import { Route as AppEvidenceRouteImport } from './routes/app/evidence'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppMissionsRouteImport } from './routes/app/missions'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppReadinessRouteImport } from './routes/app/readiness'
import { Route as AppSkillsRouteImport } from './routes/app/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticRoute = AppDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/profile'
    | '/app/readiness'
    | '/app/skills'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/profile'
    | '/app/readiness'
    | '/app/skills'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/profile'
    | '/app/readiness'
    | '/app/skills'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostic': {
      id: '/app/diagnostic'
      path: '/diagnostic'
      fullPath: '/app/diagnostic'
      preLoaderRoute: typeof AppDiagnosticRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppCareerRoute: typeof AppCareerRoute
  AppDiagnosticRoute: typeof AppDiagnosticRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppCareerRoute: AppCareerRoute,
  AppDiagnosticRoute: AppDiagnosticRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
