/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgentRouteImport } from './routes/app/agent'
import { Route as AppCareerRouteImport } from './routes/app/career'
import { Route as AppCoachRouteImport } from './routes/app/coach'
import { Route as AppDiagnosticRouteImport } from './routes/app/diagnostic'
import { Route as AppEvidenceRouteImport } from './routes/app/evidence'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppMissionsRouteImport } from './routes/app/missions'
import { Route as AppPathRouteImport } from './routes/app/path'
import { Route as AppPlanRouteImport } from './routes/app/plan'
import { Route as AppPracticeRouteImport } from './routes/app/practice'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppReadinessRouteImport } from './routes/app/readiness'
import { Route as AppSkillsRouteImport } from './routes/app/skills'
import { Route as AppTodayRouteImport } from './routes/app/today'
import { Route as AppInterviewInterviewIdRouteImport } from './routes/app/interview.$interviewId'
import { Route as AppLearnModuleCodeRouteImport } from './routes/app/learn.$moduleCode'
import { Route as AppProjectsProjectCodeRouteImport } from './routes/app/projects.$projectCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticRoute = AppDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppPathRoute = AppPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewInterviewIdRoute = AppInterviewInterviewIdRouteImport.update({
  id: '/interview/$interviewId',
  path: '/interview/$interviewId',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnModuleCodeRoute = AppLearnModuleCodeRouteImport.update({
  id: '/learn/$moduleCode',
  path: '/learn/$moduleCode',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectCodeRoute = AppProjectsProjectCodeRouteImport.update({
  id: '/projects/$projectCode',
  path: '/projects/$projectCode',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/path': typeof AppPathRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/today': typeof AppTodayRoute
  '/app/': typeof AppIndexRoute
  '/app/interview/$interviewId': typeof AppInterviewInterviewIdRoute
  '/app/learn/$moduleCode': typeof AppLearnModuleCodeRoute
  '/app/projects/$projectCode': typeof AppProjectsProjectCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/path': typeof AppPathRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/today': typeof AppTodayRoute
  '/app': typeof AppIndexRoute
  '/app/interview/$interviewId': typeof AppInterviewInterviewIdRoute
  '/app/learn/$moduleCode': typeof AppLearnModuleCodeRoute
  '/app/projects/$projectCode': typeof AppProjectsProjectCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agent': typeof AppAgentRoute
  '/app/career': typeof AppCareerRoute
  '/app/coach': typeof AppCoachRoute
  '/app/diagnostic': typeof AppDiagnosticRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/path': typeof AppPathRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/today': typeof AppTodayRoute
  '/app/': typeof AppIndexRoute
  '/app/interview/$interviewId': typeof AppInterviewInterviewIdRoute
  '/app/learn/$moduleCode': typeof AppLearnModuleCodeRoute
  '/app/projects/$projectCode': typeof AppProjectsProjectCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/coach'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/path'
    | '/app/plan'
    | '/app/practice'
    | '/app/profile'
    | '/app/progress'
    | '/app/readiness'
    | '/app/skills'
    | '/app/today'
    | '/app/'
    | '/app/interview/$interviewId'
    | '/app/learn/$moduleCode'
    | '/app/projects/$projectCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/coach'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/path'
    | '/app/plan'
    | '/app/practice'
    | '/app/profile'
    | '/app/progress'
    | '/app/readiness'
    | '/app/skills'
    | '/app/today'
    | '/app'
    | '/app/interview/$interviewId'
    | '/app/learn/$moduleCode'
    | '/app/projects/$projectCode'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agent'
    | '/app/career'
    | '/app/coach'
    | '/app/diagnostic'
    | '/app/evidence'
    | '/app/explore'
    | '/app/home'
    | '/app/missions'
    | '/app/path'
    | '/app/plan'
    | '/app/practice'
    | '/app/profile'
    | '/app/progress'
    | '/app/readiness'
    | '/app/skills'
    | '/app/today'
    | '/app/'
    | '/app/interview/$interviewId'
    | '/app/learn/$moduleCode'
    | '/app/projects/$projectCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostic': {
      id: '/app/diagnostic'
      path: '/diagnostic'
      fullPath: '/app/diagnostic'
      preLoaderRoute: typeof AppDiagnosticRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/path': {
      id: '/app/path'
      path: '/path'
      fullPath: '/app/path'
      preLoaderRoute: typeof AppPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice': {
      id: '/app/practice'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interview/$interviewId': {
      id: '/app/interview/$interviewId'
      path: '/interview/$interviewId'
      fullPath: '/app/interview/$interviewId'
      preLoaderRoute: typeof AppInterviewInterviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/$moduleCode': {
      id: '/app/learn/$moduleCode'
      path: '/learn/$moduleCode'
      fullPath: '/app/learn/$moduleCode'
      preLoaderRoute: typeof AppLearnModuleCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectCode': {
      id: '/app/projects/$projectCode'
      path: '/projects/$projectCode'
      fullPath: '/app/projects/$projectCode'
      preLoaderRoute: typeof AppProjectsProjectCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppCareerRoute: typeof AppCareerRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDiagnosticRoute: typeof AppDiagnosticRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppPathRoute: typeof AppPathRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInterviewInterviewIdRoute: typeof AppInterviewInterviewIdRoute
  AppLearnModuleCodeRoute: typeof AppLearnModuleCodeRoute
  AppProjectsProjectCodeRoute: typeof AppProjectsProjectCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppCareerRoute: AppCareerRoute,
  AppCoachRoute: AppCoachRoute,
  AppDiagnosticRoute: AppDiagnosticRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppPathRoute: AppPathRoute,
  AppPlanRoute: AppPlanRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppInterviewInterviewIdRoute: AppInterviewInterviewIdRoute,
  AppLearnModuleCodeRoute: AppLearnModuleCodeRoute,
  AppProjectsProjectCodeRoute: AppProjectsProjectCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
